main/routes/randomForestRoute.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request, g, send_file, Response
from collections import Counter
import pandas as pd
import joblib, base64, re
from main.models.dbModel import Users, Subprogram, Pending_project
from main import db

randomForest_Route = Blueprint('randomForest', __name__)

model_path_cesu = 'trained_modelCESU7.pkl'
sub_model_path = 'subprogram7.pkl'

#comments

model = joblib.load(model_path_cesu)
model2 = joblib.load(sub_model_path)


@randomForest_Route.errorhandler(Exception)
def handle_error(e):
    if g.current_role == "Coordinator":
        return render_template("cerror.html"), 500  # Customize the error page and status code
    else:
        return render_template("error.html"), 500  # Customize the error page and status code
  
def get_current_user():
    if 'user_id' in session:
        # Assuming you have a User model or some way to fetch the user by ID
        user = Users.query.get(session['user_id'])
        pending_count = Pending_project.query.filter_by(status="For Review").count()
            
        # Set a maximum value for pending_count
        max_pending_count = 9
        pending_count_display = min(pending_count, max_pending_count)
        pending_count_display = '9+' if pending_count > max_pending_count else pending_count


        declined_count = Pending_project.query.filter_by(status="Declined", program=user.program).count() 
        max_declined_count = 9
        declined_count_display = min(declined_count, max_declined_count)
        declined_count_display = '9+' if declined_count > max_declined_count else declined_count
        
        profile_picture_base64 = None
        if user:
            if user.profile_picture:
                # Convert the profile picture to base64 encoding
                profile_picture_base64 = base64.b64encode(user.profile_picture).decode('utf-8')
            return user.username, user.role, pending_count_display, declined_count_display, user.firstname, user.lastname, profile_picture_base64
    return None, None, 0, 0, None, None, None

@randomForest_Route.before_request
def before_request():
    g.current_user, g.current_role, g.pending_count_display, g.declined_count_display, g.current_firstname, g.current_lastname, g.profile_picture_base64 = get_current_user()

@randomForest_Route.context_processor
def inject_current_user():
    return dict(current_user=g.current_user, current_role=g.current_role, pending_count = g.pending_count_display, declined_count=g.declined_count_display, current_firstname=g.current_firstname, current_lastname=g.current_lastname, profile_picture_base64 = g.profile_picture_base64 )

@randomForest_Route.route("/program", methods=["GET", "POST"])
def program():
    if g.current_role != "Admin" and g.current_role != "BOR":
        return redirect(url_for('dbModel.login'))
        
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))

    return render_template("program.html")

@randomForest_Route.route("/cProgram", methods=["GET", "POST"])
def cProgram():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))

    return render_template("cProgram.html")

#######################################################################

@randomForest_Route.route("/programWithCSV", methods=["GET", "POST"])
def programWithCSV():
    if g.current_role != "Admin" and g.current_role != "BOR":
        return redirect(url_for('dbModel.login'))
    
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))

    if request.method == "POST":
        csv_file = request.files["csv_file"]
      
        if csv_file:
            df = pd.read_csv(csv_file)
            df = df.iloc[:, 3:]
            columns_with_strings = df.select_dtypes(include=['object']).columns

            sub_programs_dict = {
                "Literacy": db.session.query(Subprogram).filter(Subprogram.program == "Literacy").all(),
                "Socio-economic": db.session.query(Subprogram).filter(Subprogram.program == "Socio-economic").all(),
                "Environmental Stewardship": db.session.query(Subprogram).filter(Subprogram.program == "Environmental Stewardship").all(),
                "Health and Wellness": db.session.query(Subprogram).filter(Subprogram.program == "Health and Wellness").all(),
                "Cultural Enhancement": db.session.query(Subprogram).filter(Subprogram.program == "Cultural Enhancement").all(),
                "Values Formation": db.session.query(Subprogram).filter(Subprogram.program == "Values Formation").all(),
                "Disaster Management": db.session.query(Subprogram).filter(Subprogram.program == "Disaster Management").all(),
                "Gender and Development": db.session.query(Subprogram).filter(Subprogram.program == "Gender and Development").all()
            }

            if not columns_with_strings.empty:
                encoding_dict_kasarian = {'Lalake': 0, 'Babae': 1}
                encoding_dict_edad = {'17-below': 0, '18-24': 1, '25-34': 2, '35-44': 3, '45-54': 4, '55-64': 5, '65-Above': 6}
                encoding_dict_antas = {'Hindi nakapagtapos ng Elementarya':0, 'Elementarya':1, 'Hindi nakapagtapos ng Sekundarya':2, 'Sekundarya':3, 'Kolehiyo':4, 'Hindi nakapagtapos ng Kolehiyo':5, 'Masters Degree':6, 'Doctorate Degree':7, 'Hindi nakapag-aral':8}
                encoding_dict_uri = {'May Trabaho': 1, 'Walang Trabaho': 0}

                endcoding_dict_Pangedukasyon = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pangkultura = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pangkabuhayan = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Values = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pagtatanim = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pagkain = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pangkalusugan = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Pagrerecycle = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Dental = {'Oo':1, 'Hindi': 0}
                endcoding_dict_Teknolohiya = {'Oo':1, 'Hindi': 0}

                df['Kasarian'] = df['Kasarian'].map(encoding_dict_kasarian)
                df['Edad'] = df['Edad'].map(encoding_dict_edad)
                df['Antas na tinapos'] = df['Antas na tinapos'].map(encoding_dict_antas)
                df['Uri ng trabaho'] = df['Uri ng trabaho'].map(encoding_dict_uri)
                df['Serbisyong Pangedukasyon'] = df['Serbisyong Pangedukasyon'].map(endcoding_dict_Pangedukasyon)
                df['Pagsasanay Pangkabuhayan (Livelihood)'] = df['Pagsasanay Pangkabuhayan (Livelihood)'].map(endcoding_dict_Pangkabuhayan)
                df['Pagtatanim'] = df['Pagtatanim'].map(endcoding_dict_Pagtatanim)
                df['Serbisyong Pangkalusugan'] = df['Serbisyong Pangkalusugan'].map(endcoding_dict_Pangkalusugan)
                df['Serbisyong Dental'] = df['Serbisyong Dental'].map(endcoding_dict_Dental)
                df['Kaalamang Pangkultura'] = df['Kaalamang Pangkultura'].map(endcoding_dict_Pangkultura)
                df['Values Formation at Moral Recovery'] = df['Values Formation at Moral Recovery'].map(endcoding_dict_Values)
                df['Ayudang Pagkain (Food Assistance)'] = df['Ayudang Pagkain (Food Assistance)'].map(endcoding_dict_Pagkain)
                df['Pagrerecycle'] = df['Pagrerecycle'].map(endcoding_dict_Pagrerecycle)
                df['Pagsasanay Ukol sa Teknolohiya'] = df['Pagsasanay Ukol sa Teknolohiya'].map(endcoding_dict_Teknolohiya)
                

            if "Program" in df.columns:
                target_variable = "Program"
                X = df.drop(target_variable, axis=1)
                predictions = model.predict(X)
                df["Program"] = predictions

            else:
                predictions = model.predict(df)
                df["Program"] = predictions

            #FOR SUBPROGRAM PREDICTION

            encoding_dict_program = {'Literacy': 0, 'Socio-economic': 1, 'Environmental Stewardship': 2, 'Health and Wellness': 3, 'Cultural Enhancement': 4, 'Values Formation': 5, 'Disaster Management': 6, 'Gender and Development': 7}  # Define your categories and values
            df['Program'] = df['Program'].map(encoding_dict_program)

            if "Sub Program" in df.columns:
                target_variable = "Sub Program"
                X = df.drop(target_variable, axis=1)
                predictions2 = model2.predict(X)
                df["Sub Program"] = predictions2
            else:
                predictions2 = model2.predict(df)
                df["Sub Program"] = predictions2

            result_csv_filename = "result.csv"  # Specify the filename you want
            df.to_csv(result_csv_filename, index=False)

            df = pd.read_csv(result_csv_filename)
            columns_with_strings = df.select_dtypes(include=['object']).columns
            prediction_counts2 = Counter(predictions2)
            top_3_predictions2 = prediction_counts2.most_common(3)

            top_programs_with_subprograms2 = []
            for prediction2, count in top_3_predictions2:
                top_programs_with_subprograms2.append({
                    "program": prediction2,
                    "quantity": count
                   
            })
            #END of subprogram prediction


            prediction_counts = Counter(predictions)

            # Find the top 3 most frequent predictions
            top_3_predictions = prediction_counts.most_common(3)

             # Pass the top programs and their sub-programs to the template
            top_programs_with_subprograms = []
            for prediction, count in top_3_predictions:
                top_programs_with_subprograms.append({
                    "program": prediction,
                    "quantity": count,

main/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CESU | {% block title %}{% endblock %}</title>

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <link rel="stylesheet" href="/static/css/admin_dashboard.css">
    <link rel="stylesheet" href="/static/css/programCSVresult.css">
    <link rel="stylesheet" href="/static/css/community.css">
    <link rel="stylesheet" href="/static/css/manage_account.css">
    <link rel="stylesheet" href="/static/css/coordinator.css">
    <link rel="stylesheet" href="/static/css/program.css">
    <link rel="stylesheet" href="/static/css/dlfiles.css">
    <link rel="stylesheet" href="/static/css/kaakbay_program.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="/static/css/change_password.css">
    <link rel="stylesheet" href="/static/css/flash.css">
    <link rel="stylesheet" href="/static/css/pending.css">
    <link rel="stylesheet" href="/static/css/pending_details.css">
    <link rel="stylesheet" href="/static/css/project_files.css">
    <link rel="stylesheet" href="/static/css/project_table.css">
    <link rel="stylesheet" href="/static/css/project_details.css">
    <link rel="stylesheet" href="/static/css/archived_details.css">
    <link rel="stylesheet" href="/static/css/archived_files.css">
    <link rel="stylesheet" href="/static/css/archived_table.css">
    <link rel="stylesheet" href="/static/css/cesu_plans.css">
    <link rel="stylesheet" href="/static/css/Logfile.css">
    <link rel="stylesheet" href="/static/css/plan_details.css">
    <link rel="stylesheet" href="/static/css/fund.css">
    <link rel="stylesheet" href="/static/css/edit_profile.css">
    <link rel="stylesheet" href="/static/css/resources.css">

    <link rel="stylesheet" href="/static/css/tooltip.css">
    <link class="favicon" rel="icon" href="{{ url_for('static', filename='images/cesu-icon.ico') }}"
        type="image/x-icon">

    <style>
        @media screen and (max-width: 400px) {


            .invert-blue {
                content: url("/static/images/user-invert-blue.png");
                /* Change the image source for mobile */
            }
        }
    </style>
</head>

<body>
    <div class="container1 ">
        <aside class="sticky-top">
            <div class="top">
                <div class="logo">
                    <img src="/static/images/mobile.png" alt="CESU-LOGO">
                    <span class="cesu" id="dashboardLink">CE
                        <span class="su blue-link">SU</span>
                    </span>
                </div>
                <span class="cesu-mobile" id="dashboardLink2">CE
                    <span class="su-mobile blue-link">SU</span>
                </span>
                <div class="close" id="close-btn">
                    <span class="material-symbols-sharp">close</span>
                </div>
            </div>
            <div class="sidebar">
                <a href="{{ url_for('dbModel.dashboard') }}" class="sidebar-link " style="display:none;">
                    <span class="material-symbols-sharp">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{ url_for('dbModel.manage_community') }} " class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">groups</span>
                    <h3>Community</h3>
                </a>
                <a href="{{ url_for('dbModel.cesu_plans') }}" class="sidebar-link pending-container blue-link">
                    <span class="material-symbols-outlined">
                        notes
                    </span>
                    <h3>CESU Plans and Programs</h3>

                </a>
                <a href="{{ url_for('dbModel.kaakbay_program') }} " class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">
                        monitoring
                    </span>
                    <h3>Extension/Out Reach Programs
                    </h3>
                </a>

                <a href="{{ url_for('dbModel.manage_pending') }}" class="sidebar-link pending-container blue-link">
                    <span class="material-symbols-sharp">
                        pending
                    </span>
                    <h3>Pending Projects</h3>
                    <span class="pending-badge" id="pending-badge">{{pending_count}}</span>
                </a>
                <a href="{{ url_for('dbModel.manage_account') }}" class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">manage_accounts</span>
                    <h3>Users Account</h3>
                </a>

                <a href="{{ url_for('randomForest.program') }}" class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">neurology</span>
                    <h3>Program Recommendation</h3>
                </a>

                <a href="{{ url_for('dbModel.fund') }}" class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">crowdsource</span>
                    <h3>Fundraiser</h3>
                </a>


                <a href="{{ url_for('dbModel.logs_activity') }}" class="sidebar-link blue-link">
                    <span class="material-symbols-sharp">manage_search</span>
                    <h3>Logs</h3>
                </a>
                <div class="dropdown-files" onclick="toggleDropdownFile()">
                    <a href="#" class="sidebar-link blue-link">
                        <span class="material-symbols-sharp">
                            folder
                        </span>
                        <h3>Files</h3>
                        <span class="material-symbols-sharp arrow_drop_down">
                            arrow_drop_down
                        </span>
                    </a>
                    <div class="dropdown-content-files" id="dropdown-content-files">
                        <a class="blue-link" href="{{ url_for('file.files') }}">CESU files</a>

                        <a class="blue-link" href="{{ url_for('dbModel.archived_files') }}">Archived files</a>
                        <a class="blue-link" href="{{ url_for('dbModel.resources') }}">Resources</a>
                        <a class="blue-link" href="{{ url_for('dbModel.project_files') }}">Community projects file</a>
                    </div>
                </div>

            </div>
        </aside>
        <main>
            {% block content %}{% endblock %}

            <div class="space" style="margin-top: 5rem;"></div>
        </main>
        <div class="right">
            <div class="top top-blue">
                <button id="menu-btn">
                    <span class="material-symbols-sharp">menu</span>
                </button>

                <div class="theme-toggler">
                    <span class="material-symbols-sharp active">light_mode</span>
                    <span class="material-symbols-sharp">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="profile-info">
                        <p>Hi, <b style="text-transform: uppercase;">{{current_firstname}}
                                <span>{{current_lastname}}</span></b></p>
                        <small class="text-muted">{{current_role}}</small>
                    </div>
                    <div class="profile-photo" id="profile-photo" onclick="toggleDropdown()">
                        {% if profile_picture_base64 %}
                        <img src="data:image/jpeg;base64,{{ profile_picture_base64 }}" alt="Profile Picture">
                        {% else %}
                        <img class="invert-blue" src="/static/images/user-blue.png" alt="CESU-LOGO">
                        {% endif %}

                        <div class="dropdown-content" id="dropdown-content">

                            <div class="edit-hover"><a class="edit-button edit-button-blue"
                                    href="{{ url_for('dbModel.edit_profile') }}" id="edit-button">Edit
                                    Profile</a></div>

                            <div class="password-div password-div-blue"><a class="password-button password-button-blue"
                                    href="{{ url_for('dbModel.change_password') }}" id="password-button">Change
                                    Password</a></div>

                            <div class="logout-hover "><a class="logout-button logout-button-blue"
                                    href="{{ url_for('dbModel.clear_session') }}" id="logout-button"
                                    onclick="clearAndSetFirstLinkActive();">Logout</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End of top-->
            <div class="recent-updates">

                <div class="updates">

                    <div id="date-container">
                        <!-- The current date and day will be displayed here -->
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="/static/js/admin_dashboard.js"></script>

    <script>
        function toggleDropdownFile() {
            var dropdownContent = document.getElementById("dropdown-content-files");
            dropdownContent.style.display = (dropdownContent.style.display === "block") ? "none" : "block";
        }
    </script>
    <script>
        var pendingCount = '{{pending_count}}'; // Assuming pending_count is a variable in your template

        // Get the element by ID
        var pendingBadge = document.getElementById('pending-badge');

        // Set the display property based on the value of pendingCount
        pendingBadge.style.display = pendingCount >= 1 ? 'block' : 'none';
    </script>

    <!-- ON CLICK CESU-->
    <script>
        document.getElementById("dashboardLink").addEventListener("click", function () {
            window.location.href = "{{ url_for('dbModel.dashboard') }}";
        });
        document.getElementById("dashboardLink2").addEventListener("click", function () {
            window.location.href = "{{ url_for('dbModel.dashboard') }}";
        });
    </script>
</body>

</html>

main/templates/archived_table.html
{% extends "admin_dashboard.html" %}
{% block title %}Archived Project{% endblock %}
{% block content %}
<div class="margin-top"></div>
{% with messages = get_flashed_messages(category_filter=['delete_pending'], with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="flash flash-{{ category }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="archived_table">
    <div class="jumbotron">
        <div class="for_filter">
            <div class="year-filter1 ">
                <label for="year">Select Year:</label>
                <select id="year" onchange="filterByYear()">
                    {% for year in range(current_year, current_year + 5) %}
                    <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
                <button class="show-all-button" onclick="showAllData()">Show All</button>
            </div>
        <h2 style="margin-bottom: 1rem;">{{data}} <b>Archived Projects</b></h2>
        </div>
        <div class="table-card">
            <table class="table table-striped" id="logs_table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Community</th>
                        <th>Program</th>
                        <th>Sub-Program</th>
                        <th>Week</th>
                        <th>Start Date</th>
                        <th>Total Week</th>
                        <th>Coordinator</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                {% for row in archived_file_list %}
                <tbody>
                    <tr>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.id
                                }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.community }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.program }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.subprogram }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.week
                                }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">
                                {{ row.start_date }}</a></td>

                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.totalWeek }}</a></td>
                        <td><a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}" class="btn-edit">{{
                                row.user
                                }}</a></td>
                        <td>
                            <a href="{{ url_for('dbModel.view_archived', project_id=row.id)}}"
                                class="btn-edit status-element" data-status="{{ row.status }}">
                                {{ row.status }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('dbModel.delete_archived', project_id=row.id, data=data)}}"
                                class="btn-delete1" onclick="return confirm('Are you sure to delete?')">Delete</a>
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
            <p id="noRecordsMessage" style="display: none;">No records found.</p>
        </div> <!--end jumbotron-->
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var statusElements = document.querySelectorAll('.status-element');
        statusElements.forEach(function (statusElement) {
            var status = statusElement.getAttribute('data-status');
            if (status.trim() === 'Ongoing') {
                statusElement.style.color = 'orange';  // Change the color as needed

            } else {
                statusElement.style.color = '#00e600';
            }
        });
    });
</script>

<script>
    function filterByYear() {
        var selectedYear = $("#year").val();
        var recordsFound = false;

        $("#logs_table tbody tr").each(function () {
            var rowYear = parseInt($(this).find("td:eq(5)").text().split('-')[0]);
            if (rowYear === parseInt(selectedYear) || selectedYear === "All") {
                $(this).show();
                recordsFound = true;
            } else {
                $(this).hide();
            }
        });

        // Display or hide the "No records found" message
        if (recordsFound) {
            $("#noRecordsMessage").hide();
        } else {
            $("#noRecordsMessage").show();
        }
    }

    function showAllData() {
        // Show all rows
        $("#logs_table tbody tr").show();

        // Hide the "No records found" message
        $("#noRecordsMessage").hide();
    }
</script>

{% endblock %}

main/templates/cPending.html
{% extends "coordinator_dashboard.html" %}
{% block title %}Pending{% endblock %}
{% block content %}
<div class="margin-top"></div>
{% with messages = get_flashed_messages(category_filter=['delete_pending'], with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="flash flash-{{ category }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="cpendingCard">
    <div class="pendingBox">
        <div class="jumbotron">
            <h2 style="margin-bottom: 1rem;">Pending <b>Projects</b></h2>
            <div class="table-card">
                <table class="table" id="data-table">
                    <tr>
                        <th>ID</th>
                        <th>Community</th>
                        <th>Program</th>
                        <th>Sub-Program</th>

                        <th>Total Week</th>
                        <th>Coordinator</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    {% for row in pending_project_data %}
                    <tr>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.id }}</a></td>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.community }}</a></td>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.program }}</a></td>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.subprogram }}</a></td>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.totalWeek }}</a></td>
                        <td><a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}" class="btn-edit">{{
                                row.user }}</a></td>
                        <td>
                            <a href="{{ url_for('coordinator.cView_pending', pending_id=row.id)}}"
                                class="btn-edit status-element" data-status="{{ row.status }}">
                                {{ row.status }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('coordinator.cDelete_pending', id=row.id)}}" class="btn-delete1"
                                onclick="return confirm('Are you sure to delete?')">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div> <!--end jumbotron-->
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var statusElements = document.querySelectorAll('.status-element');
        statusElements.forEach(function (statusElement) {
            var status = statusElement.getAttribute('data-status');
            if (status.trim() === 'Declined') {
                statusElement.style.color = 'red';  // Change the color as needed

            } else {
                statusElement.style.color = '#0066ff';
            }
        });
    });
</script>


<script>
    flatpickr("#start_date_input", {
        dateFormat: "Y-m-d",
        altInput: true,
        altFormat: "F j, Y"
    });

    flatpickr("#end_date_input", {
        dateFormat: "Y-m-d",
        altInput: true,
        altFormat: "F j, Y"
    });
</script>

{% endblock %}

main/templates/password_recovery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Recovery</title>
</head>
<body>
    <h2>Password Recovery for {{ email }}</h2>
    <form action="{{ url_for('dbModel.recover_password') }}" method="POST">
        <input type="hidden" name="email" value="{{ email }}">
        <label for="otp">Enter the OTP sent to your email:</label>
        <input type="text" id="otp" name="otp" required>
        <label for="new_password">Enter your new password:</label>
        <input type="password" id="new_password" name="new_password" required>
        <button type="submit">Recover Password</button>
    </form>
</body>
</html>